package cn.edu.upc.manage.dao;

import cn.edu.upc.manage.model.GroupEx;

public interface GroupExMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group_ex
     *
     * @mbg.generated Tue Mar 17 22:10:51 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group_ex
     *
     * @mbg.generated Tue Mar 17 22:10:51 CST 2020
     */
    int insert(GroupEx record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group_ex
     *
     * @mbg.generated Tue Mar 17 22:10:51 CST 2020
     */
    int insertSelective(GroupEx record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group_ex
     *
     * @mbg.generated Tue Mar 17 22:10:51 CST 2020
     */
    GroupEx selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group_ex
     *
     * @mbg.generated Tue Mar 17 22:10:51 CST 2020
     */
    int updateByPrimaryKeySelective(GroupEx record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group_ex
     *
     * @mbg.generated Tue Mar 17 22:10:51 CST 2020
     */
    int updateByPrimaryKey(GroupEx record);
}