package cn.edu.upc.manage.dao;

import cn.edu.upc.manage.model.Project;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface ProjectMapper {

    List<Project> selectByProjectName(@Param("projectName") String  projectName);
    /**
     * 获取全部项目
     *
     * @return
     */
    List<Project> getProjectList();


    /**
     * 增加项目
     *
     * @param project
     * @return
     */
    int addProject(Project project);

    /**
     * 删除某个项目
     *
     * @param id
     * @return
     */
    int deleteProject(Project id);
    List<String> getProjectName ();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project
     *
     * @mbg.generated Tue Mar 17 22:34:04 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project
     *
     * @mbg.generated Tue Mar 17 22:34:04 CST 2020
     */
    int insert(Project record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project
     *
     * @mbg.generated Tue Mar 17 22:34:04 CST 2020
     */
    int insertSelective(Project record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project
     *
     * @mbg.generated Tue Mar 17 22:34:04 CST 2020
     */
    Project selectByPrimaryKey(Integer id);

    List<Project> selectByManager(Integer managerId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project
     *
     * @mbg.generated Tue Mar 17 22:34:04 CST 2020
     */
    int updateByPrimaryKeySelective(Project record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project
     *
     * @mbg.generated Tue Mar 17 22:34:04 CST 2020
     */
    int updateByPrimaryKey(Project record);
}