package cn.edu.upc.manage.dao;

import cn.edu.upc.manage.model.RightRole;

import java.util.List;

public interface RightRoleMapper {

    void deleteRightRoleLN(Long id);
    List<RightRole> selectByRoleIdLN(Long id);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table right_role
     *
     * @mbg.generated Fri Apr 03 14:55:11 CST 2020
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table right_role
     *
     * @mbg.generated Fri Apr 03 14:55:11 CST 2020
     */
    int insert(RightRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table right_role
     *
     * @mbg.generated Fri Apr 03 14:55:11 CST 2020
     */
    int insertSelective(RightRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table right_role
     *
     * @mbg.generated Fri Apr 03 14:55:11 CST 2020
     */
    RightRole selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table right_role
     *
     * @mbg.generated Fri Apr 03 14:55:11 CST 2020
     */
    int updateByPrimaryKeySelective(RightRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table right_role
     *
     * @mbg.generated Fri Apr 03 14:55:11 CST 2020
     */
    int updateByPrimaryKey(RightRole record);
}