package cn.edu.upc.manage.dao;

import cn.edu.upc.manage.model.Rights;
import cn.edu.upc.manage.model.RightsSetLN;
import org.springframework.stereotype.Repository;

import java.util.List;
@Repository
public interface RightsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rights
     *
     * @mbg.generated Thu Mar 19 17:24:21 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    int setdelFrag(Rights rights);

    List<Rights> selectAllRights();
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rights
     *
     * @mbg.generated Thu Mar 19 17:24:21 CST 2020
     */
    int insert(Rights record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rights
     *
     * @mbg.generated Thu Mar 19 17:24:21 CST 2020
     */
    int insertSelective(Rights record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rights
     *
     * @mbg.generated Thu Mar 19 17:24:21 CST 2020
     */
    Rights selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rights
     *
     * @mbg.generated Thu Mar 19 17:24:21 CST 2020
     */
    int updateByPrimaryKeySelective(Rights record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rights
     *
     * @mbg.generated Thu Mar 19 17:24:21 CST 2020
     */
    int updateByPrimaryKey(Rights record);

    /**---------------------刘宁--------------------- */
    List<RightsSetLN> selectAllRightsLN();
    Rights selectByPrimaryKeyLN(Long id);
}