package cn.edu.upc.manage.dao;

import cn.edu.upc.manage.model.RightRoleInput;
import cn.edu.upc.manage.model.Role;

import java.util.List;

public interface RoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role
     *
     * @mbg.generated Thu Apr 02 16:19:53 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    void deleteRoleLN(Long id);
    void updateRoleName(RightRoleInput rightRoleInput);
    Role selectRoles(Integer id);
    int setdelFlag(Role role);
    List<Role> selectAllRole();

    int selectLastInsert();
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role
     *
     * @mbg.generated Thu Apr 02 16:19:53 CST 2020
     */
    int insert(Role record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role
     *
     * @mbg.generated Thu Apr 02 16:19:53 CST 2020
     */
    int insertSelective(Role record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role
     *
     * @mbg.generated Thu Apr 02 16:19:53 CST 2020
     */
    Role selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role
     *
     * @mbg.generated Thu Apr 02 16:19:53 CST 2020
     */
    int updateByPrimaryKeySelective(Role record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role
     *
     * @mbg.generated Thu Apr 02 16:19:53 CST 2020
     */
    int updateByPrimaryKey(Role record);
}