package cn.edu.upc.manage.dao;

import cn.edu.upc.manage.model.RolerManage;

import java.util.List;

public interface RolerManageMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table roler_manage
     *
     * @mbg.generated Fri Mar 13 14:58:24 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table roler_manage
     *
     * @mbg.generated Fri Mar 13 14:58:24 CST 2020
     */
    int insert(RolerManage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table roler_manage
     *
     * @mbg.generated Fri Mar 13 14:58:24 CST 2020
     */
    int insertSelective(RolerManage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table roler_manage
     *
     * @mbg.generated Fri Mar 13 14:58:24 CST 2020
     */
    RolerManage selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table roler_manage
     *
     * @mbg.generated Fri Mar 13 14:58:24 CST 2020
     */
    int updateByPrimaryKeySelective(RolerManage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table roler_manage
     *
     * @mbg.generated Fri Mar 13 14:58:24 CST 2020
     */
    int updateByPrimaryKey(RolerManage record);

    List<RolerManage> selectAll();
}