package cn.edu.upc.manage.dao;

import cn.edu.upc.manage.model.Technology;

import java.util.LinkedHashMap;
import java.util.List;

public interface TechnologyMapper {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table technology
     *
     * @mbg.generated Thu Mar 19 18:31:05 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table technology
     *
     * @mbg.generated Thu Mar 19 18:31:05 CST 2020
     */
    int insert(Technology record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table technology
     *
     * @mbg.generated Thu Mar 19 18:31:05 CST 2020
     */
    int insertSelective(Technology record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table technology
     *
     * @mbg.generated Thu Mar 19 18:31:05 CST 2020
     */
    Technology selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table technology
     *
     * @mbg.generated Thu Mar 19 18:31:05 CST 2020
     */
    int updateByPrimaryKeySelective(Technology record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table technology
     *
     * @mbg.generated Thu Mar 19 18:31:05 CST 2020
     */
    int updateByPrimaryKey(Technology record);

    List<LinkedHashMap<String,Object>> selectTeamStructureListTechnology();
    /**
     * This method was generated by MyBatis Generator.
     * 这个类将第一，二级Technology的id和name数据集返回
     */
    List<LinkedHashMap<String,Object>> selectTeamStructureListUser(int technologyIdSecond);
    /**
     * This method was generated by MyBatis Generator.
     * 这个类将联合groupUer和User通过technologyIdSecond返回值查出tecnolygy的相关研究组和研究人员
     */
}