package cn.edu.upc.manage.dao;

import cn.edu.upc.manage.model.ViewUser;
import cn.edu.upc.manage.model.ViewUserProject;

import java.util.List;

public interface ViewUserMapper {
    /**
     * 获取所有人员
     * 项目组信息
     * 未分页
     *
     * @param groupId
     * @return
     */
    List<ViewUserProject> getPersonList(Integer groupId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table view_user
     *
     * @mbg.generated Sun Mar 22 17:13:45 CST 2020
     */
    int insert(ViewUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table view_user
     *
     * @mbg.generated Sun Mar 22 17:13:45 CST 2020
     */
    int insertSelective(ViewUser record);
}