package cn.edu.upc.manage.dao;

import cn.edu.upc.manage.model.ViewTasks;

import java.util.List;

public interface ViewTasksMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table view_tasks
     *
     * @mbg.generated Wed Mar 18 16:11:23 CST 2020
     */
    int insert(ViewTasks record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table view_tasks
     *
     * @mbg.generated Wed Mar 18 16:11:23 CST 2020
     */
    int insertSelective(ViewTasks record);
    List<ViewTasks> getTasksList();
}