package cn.edu.upc.manage.dao;

import cn.edu.upc.manage.model.ViewProject;

import java.util.List;

/**
 * @author zhenwei
 * @date 2020/3/20
 */
public interface ViewProjectMapper {
    /**
     * 获取所有项目信息
     *
     * @return
     */
    List<ViewProject> getViewProjectList();

    /**
     * 获取某个项目信息
     *
     * @param id
     * @return
     */
    ViewProject selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table view_project
     *
     * @mbg.generated Fri Mar 20 15:26:48 CST 2020
     */
    int insert(ViewProject record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table view_project
     *
     * @mbg.generated Fri Mar 20 15:26:48 CST 2020
     */
    int insertSelective(ViewProject record);
}