package cn.edu.upc.manage.dao;

import cn.edu.upc.manage.model.ViewGroupUser2;
import cn.edu.upc.manage.model.ViewGroupUser2Example;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface ViewGroupUser2Mapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table view_group_user2
     *
     * @mbg.generated Sun Apr 05 17:16:10 CST 2020
     */
    List<ViewGroupUser2> getGroupPerson(Integer projectId);
    int insert(ViewGroupUser2 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table view_group_user2
     *
     * @mbg.generated Sun Apr 05 17:16:10 CST 2020
     */
    int insertSelective(ViewGroupUser2 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table view_group_user2
     *
     * @mbg.generated Sun Apr 05 17:16:10 CST 2020
     */
    int updateByExampleSelective(@Param("record") ViewGroupUser2 record, @Param("example") ViewGroupUser2Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table view_group_user2
     *
     * @mbg.generated Sun Apr 05 17:16:10 CST 2020
     */
    int updateByExample(@Param("record") ViewGroupUser2 record, @Param("example") ViewGroupUser2Example example);
}