package cn.edu.upc.manage.model;

public class Area {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column area.id
     *
     * @mbg.generated Fri Mar 13 09:02:16 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column area.place
     *
     * @mbg.generated Fri Mar 13 09:02:16 CST 2020
     */
    private String place;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column area.id
     *
     * @return the value of area.id
     *
     * @mbg.generated Fri Mar 13 09:02:16 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column area.id
     *
     * @param id the value for area.id
     *
     * @mbg.generated Fri Mar 13 09:02:16 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column area.place
     *
     * @return the value of area.place
     *
     * @mbg.generated Fri Mar 13 09:02:16 CST 2020
     */
    public String getPlace() {
        return place;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column area.place
     *
     * @param place the value for area.place
     *
     * @mbg.generated Fri Mar 13 09:02:16 CST 2020
     */
    public void setPlace(String place) {
        this.place = place == null ? null : place.trim();
    }
}