package cn.edu.upc.manage.model;

import java.util.Date;

public class Area {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column area.id
     *
     * @mbg.generated Mon Mar 23 15:22:32 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column area.place
     *
     * @mbg.generated Mon Mar 23 15:22:32 CST 2020
     */
    private String place;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column area.create_time
     *
     * @mbg.generated Mon Mar 23 15:22:32 CST 2020
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column area.del_flag
     *
     * @mbg.generated Mon Mar 23 15:22:32 CST 2020
     */
    private Integer delFlag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column area.operator
     *
     * @mbg.generated Mon Mar 23 15:22:32 CST 2020
     */
    private String operator;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column area.operator_ip
     *
     * @mbg.generated Mon Mar 23 15:22:32 CST 2020
     */
    private String operatorIp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column area.operator_time
     *
     * @mbg.generated Mon Mar 23 15:22:32 CST 2020
     */
    private Date operatorTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column area.id
     *
     * @return the value of area.id
     *
     * @mbg.generated Mon Mar 23 15:22:32 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column area.id
     *
     * @param id the value for area.id
     *
     * @mbg.generated Mon Mar 23 15:22:32 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column area.place
     *
     * @return the value of area.place
     *
     * @mbg.generated Mon Mar 23 15:22:32 CST 2020
     */
    public String getPlace() {
        return place;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column area.place
     *
     * @param place the value for area.place
     *
     * @mbg.generated Mon Mar 23 15:22:32 CST 2020
     */
    public void setPlace(String place) {
        this.place = place == null ? null : place.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column area.create_time
     *
     * @return the value of area.create_time
     *
     * @mbg.generated Mon Mar 23 15:22:32 CST 2020
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column area.create_time
     *
     * @param createTime the value for area.create_time
     *
     * @mbg.generated Mon Mar 23 15:22:32 CST 2020
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column area.del_flag
     *
     * @return the value of area.del_flag
     *
     * @mbg.generated Mon Mar 23 15:22:32 CST 2020
     */
    public Integer getDelFlag() {
        return delFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column area.del_flag
     *
     * @param delFlag the value for area.del_flag
     *
     * @mbg.generated Mon Mar 23 15:22:32 CST 2020
     */
    public void setDelFlag(Integer delFlag) {
        this.delFlag = delFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column area.operator
     *
     * @return the value of area.operator
     *
     * @mbg.generated Mon Mar 23 15:22:32 CST 2020
     */
    public String getOperator() {
        return operator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column area.operator
     *
     * @param operator the value for area.operator
     *
     * @mbg.generated Mon Mar 23 15:22:32 CST 2020
     */
    public void setOperator(String operator) {
        this.operator = operator == null ? null : operator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column area.operator_ip
     *
     * @return the value of area.operator_ip
     *
     * @mbg.generated Mon Mar 23 15:22:32 CST 2020
     */
    public String getOperatorIp() {
        return operatorIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column area.operator_ip
     *
     * @param operatorIp the value for area.operator_ip
     *
     * @mbg.generated Mon Mar 23 15:22:32 CST 2020
     */
    public void setOperatorIp(String operatorIp) {
        this.operatorIp = operatorIp == null ? null : operatorIp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column area.operator_time
     *
     * @return the value of area.operator_time
     *
     * @mbg.generated Mon Mar 23 15:22:32 CST 2020
     */
    public Date getOperatorTime() {
        return operatorTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column area.operator_time
     *
     * @param operatorTime the value for area.operator_time
     *
     * @mbg.generated Mon Mar 23 15:22:32 CST 2020
     */
    public void setOperatorTime(Date operatorTime) {
        this.operatorTime = operatorTime;
    }
}