package cn.edu.upc.manage.model;

import java.util.Date;

public class GroupEx {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column group_ex.id
     *
     * @mbg.generated Tue Mar 17 22:10:51 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column group_ex.project_id
     *
     * @mbg.generated Tue Mar 17 22:10:51 CST 2020
     */
    private Integer projectId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column group_ex.group_name
     *
     * @mbg.generated Tue Mar 17 22:10:51 CST 2020
     */
    private String groupName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column group_ex.create_time
     *
     * @mbg.generated Tue Mar 17 22:10:51 CST 2020
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column group_ex.del_flag
     *
     * @mbg.generated Tue Mar 17 22:10:51 CST 2020
     */
    private Integer delFlag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column group_ex.operator
     *
     * @mbg.generated Tue Mar 17 22:10:51 CST 2020
     */
    private String operator;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column group_ex.operator_ip
     *
     * @mbg.generated Tue Mar 17 22:10:51 CST 2020
     */
    private String operatorIp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column group_ex.operator_time
     *
     * @mbg.generated Tue Mar 17 22:10:51 CST 2020
     */
    private Date operatorTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column group_ex.id
     *
     * @return the value of group_ex.id
     *
     * @mbg.generated Tue Mar 17 22:10:51 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column group_ex.id
     *
     * @param id the value for group_ex.id
     *
     * @mbg.generated Tue Mar 17 22:10:51 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column group_ex.project_id
     *
     * @return the value of group_ex.project_id
     *
     * @mbg.generated Tue Mar 17 22:10:51 CST 2020
     */
    public Integer getProjectId() {
        return projectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column group_ex.project_id
     *
     * @param projectId the value for group_ex.project_id
     *
     * @mbg.generated Tue Mar 17 22:10:51 CST 2020
     */
    public void setProjectId(Integer projectId) {
        this.projectId = projectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column group_ex.group_name
     *
     * @return the value of group_ex.group_name
     *
     * @mbg.generated Tue Mar 17 22:10:51 CST 2020
     */
    public String getGroupName() {
        return groupName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column group_ex.group_name
     *
     * @param groupName the value for group_ex.group_name
     *
     * @mbg.generated Tue Mar 17 22:10:51 CST 2020
     */
    public void setGroupName(String groupName) {
        this.groupName = groupName == null ? null : groupName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column group_ex.create_time
     *
     * @return the value of group_ex.create_time
     *
     * @mbg.generated Tue Mar 17 22:10:51 CST 2020
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column group_ex.create_time
     *
     * @param createTime the value for group_ex.create_time
     *
     * @mbg.generated Tue Mar 17 22:10:51 CST 2020
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column group_ex.del_flag
     *
     * @return the value of group_ex.del_flag
     *
     * @mbg.generated Tue Mar 17 22:10:51 CST 2020
     */
    public Integer getDelFlag() {
        return delFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column group_ex.del_flag
     *
     * @param delFlag the value for group_ex.del_flag
     *
     * @mbg.generated Tue Mar 17 22:10:51 CST 2020
     */
    public void setDelFlag(Integer delFlag) {
        this.delFlag = delFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column group_ex.operator
     *
     * @return the value of group_ex.operator
     *
     * @mbg.generated Tue Mar 17 22:10:51 CST 2020
     */
    public String getOperator() {
        return operator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column group_ex.operator
     *
     * @param operator the value for group_ex.operator
     *
     * @mbg.generated Tue Mar 17 22:10:51 CST 2020
     */
    public void setOperator(String operator) {
        this.operator = operator == null ? null : operator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column group_ex.operator_ip
     *
     * @return the value of group_ex.operator_ip
     *
     * @mbg.generated Tue Mar 17 22:10:51 CST 2020
     */
    public String getOperatorIp() {
        return operatorIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column group_ex.operator_ip
     *
     * @param operatorIp the value for group_ex.operator_ip
     *
     * @mbg.generated Tue Mar 17 22:10:51 CST 2020
     */
    public void setOperatorIp(String operatorIp) {
        this.operatorIp = operatorIp == null ? null : operatorIp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column group_ex.operator_time
     *
     * @return the value of group_ex.operator_time
     *
     * @mbg.generated Tue Mar 17 22:10:51 CST 2020
     */
    public Date getOperatorTime() {
        return operatorTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column group_ex.operator_time
     *
     * @param operatorTime the value for group_ex.operator_time
     *
     * @mbg.generated Tue Mar 17 22:10:51 CST 2020
     */
    public void setOperatorTime(Date operatorTime) {
        this.operatorTime = operatorTime;
    }
}