package cn.edu.upc.manage.model;

import java.util.Date;

public class GroupUser {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column group_user.id
     *
     * @mbg.generated Tue Mar 17 22:10:51 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column group_user.group_id
     *
     * @mbg.generated Tue Mar 17 22:10:51 CST 2020
     */
    private Integer groupId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column group_user.user_id
     *
     * @mbg.generated Tue Mar 17 22:10:51 CST 2020
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column group_user.user_type
     *
     * @mbg.generated Tue Mar 17 22:10:51 CST 2020
     */
    private Byte userType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column group_user.content
     *
     * @mbg.generated Tue Mar 17 22:10:51 CST 2020
     */
    private String content;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column group_user.del_flag
     *
     * @mbg.generated Tue Mar 17 22:10:51 CST 2020
     */
    private Integer delFlag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column group_user.operator
     *
     * @mbg.generated Tue Mar 17 22:10:51 CST 2020
     */
    private String operator;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column group_user.operator_ip
     *
     * @mbg.generated Tue Mar 17 22:10:51 CST 2020
     */
    private String operatorIp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column group_user.operator_time
     *
     * @mbg.generated Tue Mar 17 22:10:51 CST 2020
     */
    private Date operatorTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column group_user.id
     *
     * @return the value of group_user.id
     *
     * @mbg.generated Tue Mar 17 22:10:51 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column group_user.id
     *
     * @param id the value for group_user.id
     *
     * @mbg.generated Tue Mar 17 22:10:51 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column group_user.group_id
     *
     * @return the value of group_user.group_id
     *
     * @mbg.generated Tue Mar 17 22:10:51 CST 2020
     */
    public Integer getGroupId() {
        return groupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column group_user.group_id
     *
     * @param groupId the value for group_user.group_id
     *
     * @mbg.generated Tue Mar 17 22:10:51 CST 2020
     */
    public void setGroupId(Integer groupId) {
        this.groupId = groupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column group_user.user_id
     *
     * @return the value of group_user.user_id
     *
     * @mbg.generated Tue Mar 17 22:10:51 CST 2020
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column group_user.user_id
     *
     * @param userId the value for group_user.user_id
     *
     * @mbg.generated Tue Mar 17 22:10:51 CST 2020
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column group_user.user_type
     *
     * @return the value of group_user.user_type
     *
     * @mbg.generated Tue Mar 17 22:10:51 CST 2020
     */
    public Byte getUserType() {
        return userType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column group_user.user_type
     *
     * @param userType the value for group_user.user_type
     *
     * @mbg.generated Tue Mar 17 22:10:51 CST 2020
     */
    public void setUserType(Byte userType) {
        this.userType = userType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column group_user.content
     *
     * @return the value of group_user.content
     *
     * @mbg.generated Tue Mar 17 22:10:51 CST 2020
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column group_user.content
     *
     * @param content the value for group_user.content
     *
     * @mbg.generated Tue Mar 17 22:10:51 CST 2020
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column group_user.del_flag
     *
     * @return the value of group_user.del_flag
     *
     * @mbg.generated Tue Mar 17 22:10:51 CST 2020
     */
    public Integer getDelFlag() {
        return delFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column group_user.del_flag
     *
     * @param delFlag the value for group_user.del_flag
     *
     * @mbg.generated Tue Mar 17 22:10:51 CST 2020
     */
    public void setDelFlag(Integer delFlag) {
        this.delFlag = delFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column group_user.operator
     *
     * @return the value of group_user.operator
     *
     * @mbg.generated Tue Mar 17 22:10:51 CST 2020
     */
    public String getOperator() {
        return operator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column group_user.operator
     *
     * @param operator the value for group_user.operator
     *
     * @mbg.generated Tue Mar 17 22:10:51 CST 2020
     */
    public void setOperator(String operator) {
        this.operator = operator == null ? null : operator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column group_user.operator_ip
     *
     * @return the value of group_user.operator_ip
     *
     * @mbg.generated Tue Mar 17 22:10:51 CST 2020
     */
    public String getOperatorIp() {
        return operatorIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column group_user.operator_ip
     *
     * @param operatorIp the value for group_user.operator_ip
     *
     * @mbg.generated Tue Mar 17 22:10:51 CST 2020
     */
    public void setOperatorIp(String operatorIp) {
        this.operatorIp = operatorIp == null ? null : operatorIp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column group_user.operator_time
     *
     * @return the value of group_user.operator_time
     *
     * @mbg.generated Tue Mar 17 22:10:51 CST 2020
     */
    public Date getOperatorTime() {
        return operatorTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column group_user.operator_time
     *
     * @param operatorTime the value for group_user.operator_time
     *
     * @mbg.generated Tue Mar 17 22:10:51 CST 2020
     */
    public void setOperatorTime(Date operatorTime) {
        this.operatorTime = operatorTime;
    }
}