package cn.edu.upc.manage.model;

public class Manage {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manage.id
     *
     * @mbg.generated Fri Mar 13 21:18:29 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manage.rights
     *
     * @mbg.generated Fri Mar 13 21:18:29 CST 2020
     */
    private String rights;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manage.technology_name
     *
     * @mbg.generated Fri Mar 13 21:18:29 CST 2020
     */
    private String technologyName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manage.id
     *
     * @return the value of manage.id
     *
     * @mbg.generated Fri Mar 13 21:18:29 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manage.id
     *
     * @param id the value for manage.id
     *
     * @mbg.generated Fri Mar 13 21:18:29 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manage.rights
     *
     * @return the value of manage.rights
     *
     * @mbg.generated Fri Mar 13 21:18:29 CST 2020
     */
    public String getRights() {
        return rights;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manage.rights
     *
     * @param rights the value for manage.rights
     *
     * @mbg.generated Fri Mar 13 21:18:29 CST 2020
     */
    public void setRights(String rights) {
        this.rights = rights == null ? null : rights.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manage.technology_name
     *
     * @return the value of manage.technology_name
     *
     * @mbg.generated Fri Mar 13 21:18:29 CST 2020
     */
    public String getTechnologyName() {
        return technologyName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manage.technology_name
     *
     * @param technologyName the value for manage.technology_name
     *
     * @mbg.generated Fri Mar 13 21:18:29 CST 2020
     */
    public void setTechnologyName(String technologyName) {
        this.technologyName = technologyName == null ? null : technologyName.trim();
    }
}