package cn.edu.upc.manage.model;

public class PrivilegeManage {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column privilege_manage.id
     *
     * @mbg.generated Fri Mar 13 14:58:24 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column privilege_manage.last_menus
     *
     * @mbg.generated Fri Mar 13 14:58:24 CST 2020
     */
    private String lastMenus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column privilege_manage.rights
     *
     * @mbg.generated Fri Mar 13 14:58:24 CST 2020
     */
    private String rights;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column privilege_manage.urls
     *
     * @mbg.generated Fri Mar 13 14:58:24 CST 2020
     */
    private String urls;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column privilege_manage.notes
     *
     * @mbg.generated Fri Mar 13 14:58:24 CST 2020
     */
    private String notes;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column privilege_manage.delete_mark
     *
     * @mbg.generated Fri Mar 13 14:58:24 CST 2020
     */
    private Integer deleteMark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column privilege_manage.id
     *
     * @return the value of privilege_manage.id
     *
     * @mbg.generated Fri Mar 13 14:58:24 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column privilege_manage.id
     *
     * @param id the value for privilege_manage.id
     *
     * @mbg.generated Fri Mar 13 14:58:24 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column privilege_manage.last_menus
     *
     * @return the value of privilege_manage.last_menus
     *
     * @mbg.generated Fri Mar 13 14:58:24 CST 2020
     */
    public String getLastMenus() {
        return lastMenus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column privilege_manage.last_menus
     *
     * @param lastMenus the value for privilege_manage.last_menus
     *
     * @mbg.generated Fri Mar 13 14:58:24 CST 2020
     */
    public void setLastMenus(String lastMenus) {
        this.lastMenus = lastMenus == null ? null : lastMenus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column privilege_manage.rights
     *
     * @return the value of privilege_manage.rights
     *
     * @mbg.generated Fri Mar 13 14:58:24 CST 2020
     */
    public String getRights() {
        return rights;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column privilege_manage.rights
     *
     * @param rights the value for privilege_manage.rights
     *
     * @mbg.generated Fri Mar 13 14:58:24 CST 2020
     */
    public void setRights(String rights) {
        this.rights = rights == null ? null : rights.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column privilege_manage.urls
     *
     * @return the value of privilege_manage.urls
     *
     * @mbg.generated Fri Mar 13 14:58:24 CST 2020
     */
    public String getUrls() {
        return urls;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column privilege_manage.urls
     *
     * @param urls the value for privilege_manage.urls
     *
     * @mbg.generated Fri Mar 13 14:58:24 CST 2020
     */
    public void setUrls(String urls) {
        this.urls = urls == null ? null : urls.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column privilege_manage.notes
     *
     * @return the value of privilege_manage.notes
     *
     * @mbg.generated Fri Mar 13 14:58:24 CST 2020
     */
    public String getNotes() {
        return notes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column privilege_manage.notes
     *
     * @param notes the value for privilege_manage.notes
     *
     * @mbg.generated Fri Mar 13 14:58:24 CST 2020
     */
    public void setNotes(String notes) {
        this.notes = notes == null ? null : notes.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column privilege_manage.delete_mark
     *
     * @return the value of privilege_manage.delete_mark
     *
     * @mbg.generated Fri Mar 13 14:58:24 CST 2020
     */
    public Integer getDeleteMark() {
        return deleteMark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column privilege_manage.delete_mark
     *
     * @param deleteMark the value for privilege_manage.delete_mark
     *
     * @mbg.generated Fri Mar 13 14:58:24 CST 2020
     */
    public void setDeleteMark(Integer deleteMark) {
        this.deleteMark = deleteMark;
    }
}