package cn.edu.upc.manage.model;

import java.util.Date;

public class Progress {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column progress.id
     *
     * @mbg.generated Fri Mar 13 09:07:48 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column progress.project_id
     *
     * @mbg.generated Fri Mar 13 09:07:48 CST 2020
     */
    private Integer projectId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column progress.progress_name
     *
     * @mbg.generated Fri Mar 13 09:07:48 CST 2020
     */
    private String progressName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column progress.begin_time
     *
     * @mbg.generated Fri Mar 13 09:07:48 CST 2020
     */
    private Date beginTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column progress.end_time
     *
     * @mbg.generated Fri Mar 13 09:07:48 CST 2020
     */
    private Date endTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column progress.problem
     *
     * @mbg.generated Fri Mar 13 09:07:48 CST 2020
     */
    private String problem;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column progress.solution
     *
     * @mbg.generated Fri Mar 13 09:07:48 CST 2020
     */
    private String solution;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column progress.del_flag
     *
     * @mbg.generated Fri Mar 13 09:07:48 CST 2020
     */
    private Integer delFlag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column progress.operator_ip
     *
     * @mbg.generated Fri Mar 13 09:07:48 CST 2020
     */
    private String operatorIp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column progress.operator_time
     *
     * @mbg.generated Fri Mar 13 09:07:48 CST 2020
     */
    private Date operatorTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column progress.id
     *
     * @return the value of progress.id
     *
     * @mbg.generated Fri Mar 13 09:07:48 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column progress.id
     *
     * @param id the value for progress.id
     *
     * @mbg.generated Fri Mar 13 09:07:48 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column progress.project_id
     *
     * @return the value of progress.project_id
     *
     * @mbg.generated Fri Mar 13 09:07:48 CST 2020
     */
    public Integer getProjectId() {
        return projectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column progress.project_id
     *
     * @param projectId the value for progress.project_id
     *
     * @mbg.generated Fri Mar 13 09:07:48 CST 2020
     */
    public void setProjectId(Integer projectId) {
        this.projectId = projectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column progress.progress_name
     *
     * @return the value of progress.progress_name
     *
     * @mbg.generated Fri Mar 13 09:07:48 CST 2020
     */
    public String getProgressName() {
        return progressName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column progress.progress_name
     *
     * @param progressName the value for progress.progress_name
     *
     * @mbg.generated Fri Mar 13 09:07:48 CST 2020
     */
    public void setProgressName(String progressName) {
        this.progressName = progressName == null ? null : progressName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column progress.begin_time
     *
     * @return the value of progress.begin_time
     *
     * @mbg.generated Fri Mar 13 09:07:48 CST 2020
     */
    public Date getBeginTime() {
        return beginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column progress.begin_time
     *
     * @param beginTime the value for progress.begin_time
     *
     * @mbg.generated Fri Mar 13 09:07:48 CST 2020
     */
    public void setBeginTime(Date beginTime) {
        this.beginTime = beginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column progress.end_time
     *
     * @return the value of progress.end_time
     *
     * @mbg.generated Fri Mar 13 09:07:48 CST 2020
     */
    public Date getEndTime() {
        return endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column progress.end_time
     *
     * @param endTime the value for progress.end_time
     *
     * @mbg.generated Fri Mar 13 09:07:48 CST 2020
     */
    public void setEndTime(Date endTime) {
        this.endTime = endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column progress.problem
     *
     * @return the value of progress.problem
     *
     * @mbg.generated Fri Mar 13 09:07:48 CST 2020
     */
    public String getProblem() {
        return problem;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column progress.problem
     *
     * @param problem the value for progress.problem
     *
     * @mbg.generated Fri Mar 13 09:07:48 CST 2020
     */
    public void setProblem(String problem) {
        this.problem = problem == null ? null : problem.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column progress.solution
     *
     * @return the value of progress.solution
     *
     * @mbg.generated Fri Mar 13 09:07:48 CST 2020
     */
    public String getSolution() {
        return solution;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column progress.solution
     *
     * @param solution the value for progress.solution
     *
     * @mbg.generated Fri Mar 13 09:07:48 CST 2020
     */
    public void setSolution(String solution) {
        this.solution = solution == null ? null : solution.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column progress.del_flag
     *
     * @return the value of progress.del_flag
     *
     * @mbg.generated Fri Mar 13 09:07:48 CST 2020
     */
    public Integer getDelFlag() {
        return delFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column progress.del_flag
     *
     * @param delFlag the value for progress.del_flag
     *
     * @mbg.generated Fri Mar 13 09:07:48 CST 2020
     */
    public void setDelFlag(Integer delFlag) {
        this.delFlag = delFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column progress.operator_ip
     *
     * @return the value of progress.operator_ip
     *
     * @mbg.generated Fri Mar 13 09:07:48 CST 2020
     */
    public String getOperatorIp() {
        return operatorIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column progress.operator_ip
     *
     * @param operatorIp the value for progress.operator_ip
     *
     * @mbg.generated Fri Mar 13 09:07:48 CST 2020
     */
    public void setOperatorIp(String operatorIp) {
        this.operatorIp = operatorIp == null ? null : operatorIp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column progress.operator_time
     *
     * @return the value of progress.operator_time
     *
     * @mbg.generated Fri Mar 13 09:07:48 CST 2020
     */
    public Date getOperatorTime() {
        return operatorTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column progress.operator_time
     *
     * @param operatorTime the value for progress.operator_time
     *
     * @mbg.generated Fri Mar 13 09:07:48 CST 2020
     */
    public void setOperatorTime(Date operatorTime) {
        this.operatorTime = operatorTime;
    }
}