package cn.edu.upc.manage.model;

import com.fasterxml.jackson.annotation.JsonFormat;
import org.springframework.format.annotation.DateTimeFormat;

import java.util.Date;

public class Project {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project.id
     *
     * @mbg.generated Wed Mar 11 18:56:23 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project.project_name
     *
     * @mbg.generated Wed Mar 11 18:56:23 CST 2020
     */
    private String projectName;

    /**
     * 新增的工作地点信息
     */
    private String workPlaceName;
    public String getWorkPlaceName() {
        return workPlaceName;
    }
    public void setWorkPlaceName(String workPlaceName) {
        this.workPlaceName = workPlaceName;
    }

    /**
     * 新增的管理人员姓名
     */
    private String managerName;
    public String getManagerName() {
        return managerName;
    }

    public void setManagerName(String managerName) {
        this.managerName = managerName;
    }



    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project.leader
     *
     * @mbg.generated Wed Mar 11 18:56:23 CST 2020
     */
    private Integer leader;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project.manager
     *
     * @mbg.generated Wed Mar 11 18:56:23 CST 2020
     */
    private Integer manager;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project.place
     *
     * @mbg.generated Wed Mar 11 18:56:23 CST 2020
     */
    private Integer place;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project.begin_time
     *
     * @mbg.generated Wed Mar 11 18:56:23 CST 2020
     */
    @DateTimeFormat(pattern = "yyyy-MM-dd HH:mm:ss")
    @JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss", timezone = "GMT+8")
    private Date beginTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project.end_time
     *
     * @mbg.generated Wed Mar 11 18:56:23 CST 2020
     */
    @DateTimeFormat(pattern = "yyyy-MM-dd HH:mm:ss")
    @JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss", timezone = "GMT+8")
    private Date endTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project.create_time
     *
     * @mbg.generated Wed Mar 11 18:56:23 CST 2020
     */
    @DateTimeFormat(pattern = "yyyy-MM-dd HH:mm:ss")
    @JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss", timezone = "GMT+8")
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project.remark
     *
     * @mbg.generated Wed Mar 11 18:56:23 CST 2020
     */
    private String remark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project.del_flag
     *
     * @mbg.generated Wed Mar 11 18:56:23 CST 2020
     */
    private Integer delFlag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project.operator
     *
     * @mbg.generated Wed Mar 11 18:56:23 CST 2020
     */
    private String operator;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project.operator_ip
     *
     * @mbg.generated Wed Mar 11 18:56:23 CST 2020
     */
    private String operatorIp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project.operator_time
     *
     * @mbg.generated Wed Mar 11 18:56:23 CST 2020
     */
    @DateTimeFormat(pattern = "yyyy-MM-dd HH:mm:ss")
    @JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss", timezone = "GMT+8")
    private Date operatorTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project.id
     *
     * @return the value of project.id
     *
     * @mbg.generated Wed Mar 11 18:56:23 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project.id
     *
     * @param id the value for project.id
     *
     * @mbg.generated Wed Mar 11 18:56:23 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project.project_name
     *
     * @return the value of project.project_name
     *
     * @mbg.generated Wed Mar 11 18:56:23 CST 2020
     */
    public String getProjectName() {
        return projectName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project.project_name
     *
     * @param projectName the value for project.project_name
     *
     * @mbg.generated Wed Mar 11 18:56:23 CST 2020
     */
    public void setProjectName(String projectName) {
        this.projectName = projectName == null ? null : projectName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project.leader
     *
     * @return the value of project.leader
     *
     * @mbg.generated Wed Mar 11 18:56:23 CST 2020
     */
    public Integer getLeader() {
        return leader;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project.leader
     *
     * @param leader the value for project.leader
     *
     * @mbg.generated Wed Mar 11 18:56:23 CST 2020
     */
    public void setLeader(Integer leader) {
        this.leader = leader;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project.manager
     *
     * @return the value of project.manager
     *
     * @mbg.generated Wed Mar 11 18:56:23 CST 2020
     */
    public Integer getManager() {
        return manager;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project.manager
     *
     * @param manager the value for project.manager
     *
     * @mbg.generated Wed Mar 11 18:56:23 CST 2020
     */
    public void setManager(Integer manager) {
        this.manager = manager;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project.place
     *
     * @return the value of project.place
     *
     * @mbg.generated Wed Mar 11 18:56:23 CST 2020
     */
    public Integer getPlace() {
        return place;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project.place
     *
     * @param place the value for project.place
     *
     * @mbg.generated Wed Mar 11 18:56:23 CST 2020
     */
    public void setPlace(Integer place) {
        this.place = place;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project.begin_time
     *
     * @return the value of project.begin_time
     *
     * @mbg.generated Wed Mar 11 18:56:23 CST 2020
     */
    public Date getBeginTime() {
        return beginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project.begin_time
     *
     * @param beginTime the value for project.begin_time
     *
     * @mbg.generated Wed Mar 11 18:56:23 CST 2020
     */
    public void setBeginTime(Date beginTime) {
        this.beginTime = beginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project.end_time
     *
     * @return the value of project.end_time
     *
     * @mbg.generated Wed Mar 11 18:56:23 CST 2020
     */
    public Date getEndTime() {
        return endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project.end_time
     *
     * @param endTime the value for project.end_time
     *
     * @mbg.generated Wed Mar 11 18:56:23 CST 2020
     */
    public void setEndTime(Date endTime) {
        this.endTime = endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project.create_time
     *
     * @return the value of project.create_time
     *
     * @mbg.generated Wed Mar 11 18:56:23 CST 2020
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project.create_time
     *
     * @param createTime the value for project.create_time
     *
     * @mbg.generated Wed Mar 11 18:56:23 CST 2020
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project.remark
     *
     * @return the value of project.remark
     *
     * @mbg.generated Wed Mar 11 18:56:23 CST 2020
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project.remark
     *
     * @param remark the value for project.remark
     *
     * @mbg.generated Wed Mar 11 18:56:23 CST 2020
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project.del_flag
     *
     * @return the value of project.del_flag
     *
     * @mbg.generated Wed Mar 11 18:56:23 CST 2020
     */
    public Integer getDelFlag() {
        return delFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project.del_flag
     *
     * @param delFlag the value for project.del_flag
     *
     * @mbg.generated Wed Mar 11 18:56:23 CST 2020
     */
    public void setDelFlag(Integer delFlag) {
        this.delFlag = delFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project.operator
     *
     * @return the value of project.operator
     *
     * @mbg.generated Wed Mar 11 18:56:23 CST 2020
     */
    public String getOperator() {
        return operator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project.operator
     *
     * @param operator the value for project.operator
     *
     * @mbg.generated Wed Mar 11 18:56:23 CST 2020
     */
    public void setOperator(String operator) {
        this.operator = operator == null ? null : operator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project.operator_ip
     *
     * @return the value of project.operator_ip
     *
     * @mbg.generated Wed Mar 11 18:56:23 CST 2020
     */
    public String getOperatorIp() {
        return operatorIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project.operator_ip
     *
     * @param operatorIp the value for project.operator_ip
     *
     * @mbg.generated Wed Mar 11 18:56:23 CST 2020
     */
    public void setOperatorIp(String operatorIp) {
        this.operatorIp = operatorIp == null ? null : operatorIp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project.operator_time
     *
     * @return the value of project.operator_time
     *
     * @mbg.generated Wed Mar 11 18:56:23 CST 2020
     */
    public Date getOperatorTime() {
        return operatorTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project.operator_time
     *
     * @param operatorTime the value for project.operator_time
     *
     * @mbg.generated Wed Mar 11 18:56:23 CST 2020
     */
    public void setOperatorTime(Date operatorTime) {
        this.operatorTime = operatorTime;
    }
}