package cn.edu.upc.manage.model;

import java.util.Date;

public class Rights {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rights.id
     *
     * @mbg.generated Wed Apr 01 13:55:09 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rights.last_menus
     *
     * @mbg.generated Wed Apr 01 13:55:09 CST 2020
     */
    private Integer lastMenus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rights.rights
     *
     * @mbg.generated Wed Apr 01 13:55:09 CST 2020
     */
    private String rights;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rights.urls
     *
     * @mbg.generated Wed Apr 01 13:55:09 CST 2020
     */
    private String urls;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rights.notes
     *
     * @mbg.generated Wed Apr 01 13:55:09 CST 2020
     */
    private String notes;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rights.create_time
     *
     * @mbg.generated Wed Apr 01 13:55:09 CST 2020
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rights.del_flag
     *
     * @mbg.generated Wed Apr 01 13:55:09 CST 2020
     */
    private Integer delFlag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rights.operator
     *
     * @mbg.generated Wed Apr 01 13:55:09 CST 2020
     */
    private String operator;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rights.operator_ip
     *
     * @mbg.generated Wed Apr 01 13:55:09 CST 2020
     */
    private String operatorIp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rights.operator_time
     *
     * @mbg.generated Wed Apr 01 13:55:09 CST 2020
     */
    private Date operatorTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rights.id
     *
     * @return the value of rights.id
     *
     * @mbg.generated Wed Apr 01 13:55:09 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rights.id
     *
     * @param id the value for rights.id
     *
     * @mbg.generated Wed Apr 01 13:55:09 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rights.last_menus
     *
     * @return the value of rights.last_menus
     *
     * @mbg.generated Wed Apr 01 13:55:09 CST 2020
     */
    public Integer getLastMenus() {
        return lastMenus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rights.last_menus
     *
     * @param lastMenus the value for rights.last_menus
     *
     * @mbg.generated Wed Apr 01 13:55:09 CST 2020
     */
    public void setLastMenus(Integer lastMenus) {
        this.lastMenus = lastMenus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rights.rights
     *
     * @return the value of rights.rights
     *
     * @mbg.generated Wed Apr 01 13:55:09 CST 2020
     */
    public String getRights() {
        return rights;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rights.rights
     *
     * @param rights the value for rights.rights
     *
     * @mbg.generated Wed Apr 01 13:55:09 CST 2020
     */
    public void setRights(String rights) {
        this.rights = rights == null ? null : rights.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rights.urls
     *
     * @return the value of rights.urls
     *
     * @mbg.generated Wed Apr 01 13:55:09 CST 2020
     */
    public String getUrls() {
        return urls;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rights.urls
     *
     * @param urls the value for rights.urls
     *
     * @mbg.generated Wed Apr 01 13:55:09 CST 2020
     */
    public void setUrls(String urls) {
        this.urls = urls == null ? null : urls.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rights.notes
     *
     * @return the value of rights.notes
     *
     * @mbg.generated Wed Apr 01 13:55:09 CST 2020
     */
    public String getNotes() {
        return notes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rights.notes
     *
     * @param notes the value for rights.notes
     *
     * @mbg.generated Wed Apr 01 13:55:09 CST 2020
     */
    public void setNotes(String notes) {
        this.notes = notes == null ? null : notes.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rights.create_time
     *
     * @return the value of rights.create_time
     *
     * @mbg.generated Wed Apr 01 13:55:09 CST 2020
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rights.create_time
     *
     * @param createTime the value for rights.create_time
     *
     * @mbg.generated Wed Apr 01 13:55:09 CST 2020
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rights.del_flag
     *
     * @return the value of rights.del_flag
     *
     * @mbg.generated Wed Apr 01 13:55:09 CST 2020
     */
    public Integer getDelFlag() {
        return delFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rights.del_flag
     *
     * @param delFlag the value for rights.del_flag
     *
     * @mbg.generated Wed Apr 01 13:55:09 CST 2020
     */
    public void setDelFlag(Integer delFlag) {
        this.delFlag = delFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rights.operator
     *
     * @return the value of rights.operator
     *
     * @mbg.generated Wed Apr 01 13:55:09 CST 2020
     */
    public String getOperator() {
        return operator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rights.operator
     *
     * @param operator the value for rights.operator
     *
     * @mbg.generated Wed Apr 01 13:55:09 CST 2020
     */
    public void setOperator(String operator) {
        this.operator = operator == null ? null : operator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rights.operator_ip
     *
     * @return the value of rights.operator_ip
     *
     * @mbg.generated Wed Apr 01 13:55:09 CST 2020
     */
    public String getOperatorIp() {
        return operatorIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rights.operator_ip
     *
     * @param operatorIp the value for rights.operator_ip
     *
     * @mbg.generated Wed Apr 01 13:55:09 CST 2020
     */
    public void setOperatorIp(String operatorIp) {
        this.operatorIp = operatorIp == null ? null : operatorIp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rights.operator_time
     *
     * @return the value of rights.operator_time
     *
     * @mbg.generated Wed Apr 01 13:55:09 CST 2020
     */
    public Date getOperatorTime() {
        return operatorTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rights.operator_time
     *
     * @param operatorTime the value for rights.operator_time
     *
     * @mbg.generated Wed Apr 01 13:55:09 CST 2020
     */
    public void setOperatorTime(Date operatorTime) {
        this.operatorTime = operatorTime;
    }
}