package cn.edu.upc.manage.model;

public class RolerManage {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column roler_manage.id
     *
     * @mbg.generated Fri Mar 13 14:58:24 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column roler_manage.role_name
     *
     * @mbg.generated Fri Mar 13 14:58:24 CST 2020
     */
    private String roleName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column roler_manage.rights
     *
     * @mbg.generated Fri Mar 13 14:58:24 CST 2020
     */
    private String rights;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column roler_manage.delete_mark
     *
     * @mbg.generated Fri Mar 13 14:58:24 CST 2020
     */
    private Integer deleteMark=0;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column roler_manage.id
     *
     * @return the value of roler_manage.id
     *
     * @mbg.generated Fri Mar 13 14:58:24 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column roler_manage.id
     *
     * @param id the value for roler_manage.id
     *
     * @mbg.generated Fri Mar 13 14:58:24 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column roler_manage.role_name
     *
     * @return the value of roler_manage.role_name
     *
     * @mbg.generated Fri Mar 13 14:58:24 CST 2020
     */
    public String getRoleName() {
        return roleName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column roler_manage.role_name
     *
     * @param roleName the value for roler_manage.role_name
     *
     * @mbg.generated Fri Mar 13 14:58:24 CST 2020
     */
    public void setRoleName(String roleName) {
        this.roleName = roleName == null ? null : roleName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column roler_manage.rights
     *
     * @return the value of roler_manage.rights
     *
     * @mbg.generated Fri Mar 13 14:58:24 CST 2020
     */
    public String getRights() {
        return rights;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column roler_manage.rights
     *
     * @param rights the value for roler_manage.rights
     *
     * @mbg.generated Fri Mar 13 14:58:24 CST 2020
     */
    public void setRights(String rights) {
        this.rights = rights == null ? null : rights.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column roler_manage.delete_mark
     *
     * @return the value of roler_manage.delete_mark
     *
     * @mbg.generated Fri Mar 13 14:58:24 CST 2020
     */
    public Integer getDeleteMark() {
        return deleteMark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column roler_manage.delete_mark
     *
     * @param deleteMark the value for roler_manage.delete_mark
     *
     * @mbg.generated Fri Mar 13 14:58:24 CST 2020
     */
    public void setDeleteMark(Integer deleteMark) {
        this.deleteMark = deleteMark;
    }
}