package cn.edu.upc.manage.model;

import com.fasterxml.jackson.annotation.JsonFormat;
import org.springframework.format.annotation.DateTimeFormat;

import java.util.Date;

/**
 * @author zhenwei
 * @date 2020/3/20
 */
public class ViewProject {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column view_project.id
     *
     * @mbg.generated Fri Mar 20 15:26:48 CST 2020
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column view_project.project_name
     *
     * @mbg.generated Fri Mar 20 15:26:48 CST 2020
     */
    private String projectName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column view_project.leader
     *
     * @mbg.generated Fri Mar 20 15:26:48 CST 2020
     */
    private Integer leader;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column view_project.manager
     *
     * @mbg.generated Fri Mar 20 15:26:48 CST 2020
     */
    private Integer manager;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column view_project.begin_time
     *
     * @mbg.generated Fri Mar 20 15:26:48 CST 2020
     */
    @DateTimeFormat(pattern = "yyyy-MM-dd HH:mm:ss")
    @JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss", timezone = "GMT+8")
    private Date beginTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column view_project.end_time
     *
     * @mbg.generated Fri Mar 20 15:26:48 CST 2020
     */
    @DateTimeFormat(pattern = "yyyy-MM-dd HH:mm:ss")
    @JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss", timezone = "GMT+8")
    private Date endTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column view_project.create_time
     *
     * @mbg.generated Fri Mar 20 15:26:48 CST 2020
     */
    @DateTimeFormat(pattern = "yyyy-MM-dd HH:mm:ss")
    @JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss", timezone = "GMT+8")
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column view_project.remark
     *
     * @mbg.generated Fri Mar 20 15:26:48 CST 2020
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column view_project.del_flag
     *
     * @mbg.generated Fri Mar 20 15:26:48 CST 2020
     */
    private Integer delFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column view_project.operator
     *
     * @mbg.generated Fri Mar 20 15:26:48 CST 2020
     */
    private String operator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column view_project.operator_ip
     *
     * @mbg.generated Fri Mar 20 15:26:48 CST 2020
     */
    private String operatorIp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column view_project.operator_time
     *
     * @mbg.generated Fri Mar 20 15:26:48 CST 2020
     */
    @DateTimeFormat(pattern = "yyyy-MM-dd HH:mm:ss")
    @JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss", timezone = "GMT+8")
    private Date operatorTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column view_project.place
     *
     * @mbg.generated Fri Mar 20 15:26:48 CST 2020
     */
    private Integer place;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column view_project.work_place_name
     *
     * @mbg.generated Fri Mar 20 15:26:48 CST 2020
     */
    private String workPlaceName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column view_project.manager_name
     *
     * @mbg.generated Fri Mar 20 15:26:48 CST 2020
     */
    private String managerName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column view_project.leader_name
     *
     * @mbg.generated Fri Mar 20 15:26:48 CST 2020
     */
    private String leaderName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column view_project.id
     *
     * @return the value of view_project.id
     * @mbg.generated Fri Mar 20 15:26:48 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column view_project.id
     *
     * @param id the value for view_project.id
     * @mbg.generated Fri Mar 20 15:26:48 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column view_project.project_name
     *
     * @return the value of view_project.project_name
     * @mbg.generated Fri Mar 20 15:26:48 CST 2020
     */
    public String getProjectName() {
        return projectName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column view_project.project_name
     *
     * @param projectName the value for view_project.project_name
     * @mbg.generated Fri Mar 20 15:26:48 CST 2020
     */
    public void setProjectName(String projectName) {
        this.projectName = projectName == null ? null : projectName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column view_project.leader
     *
     * @return the value of view_project.leader
     * @mbg.generated Fri Mar 20 15:26:48 CST 2020
     */
    public Integer getLeader() {
        return leader;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column view_project.leader
     *
     * @param leader the value for view_project.leader
     * @mbg.generated Fri Mar 20 15:26:48 CST 2020
     */
    public void setLeader(Integer leader) {
        this.leader = leader;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column view_project.manager
     *
     * @return the value of view_project.manager
     * @mbg.generated Fri Mar 20 15:26:48 CST 2020
     */
    public Integer getManager() {
        return manager;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column view_project.manager
     *
     * @param manager the value for view_project.manager
     * @mbg.generated Fri Mar 20 15:26:48 CST 2020
     */
    public void setManager(Integer manager) {
        this.manager = manager;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column view_project.begin_time
     *
     * @return the value of view_project.begin_time
     * @mbg.generated Fri Mar 20 15:26:48 CST 2020
     */
    public Date getBeginTime() {
        return beginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column view_project.begin_time
     *
     * @param beginTime the value for view_project.begin_time
     * @mbg.generated Fri Mar 20 15:26:48 CST 2020
     */
    public void setBeginTime(Date beginTime) {
        this.beginTime = beginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column view_project.end_time
     *
     * @return the value of view_project.end_time
     * @mbg.generated Fri Mar 20 15:26:48 CST 2020
     */
    public Date getEndTime() {
        return endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column view_project.end_time
     *
     * @param endTime the value for view_project.end_time
     * @mbg.generated Fri Mar 20 15:26:48 CST 2020
     */
    public void setEndTime(Date endTime) {
        this.endTime = endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column view_project.create_time
     *
     * @return the value of view_project.create_time
     * @mbg.generated Fri Mar 20 15:26:48 CST 2020
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column view_project.create_time
     *
     * @param createTime the value for view_project.create_time
     * @mbg.generated Fri Mar 20 15:26:48 CST 2020
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column view_project.remark
     *
     * @return the value of view_project.remark
     * @mbg.generated Fri Mar 20 15:26:48 CST 2020
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column view_project.remark
     *
     * @param remark the value for view_project.remark
     * @mbg.generated Fri Mar 20 15:26:48 CST 2020
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column view_project.del_flag
     *
     * @return the value of view_project.del_flag
     * @mbg.generated Fri Mar 20 15:26:48 CST 2020
     */
    public Integer getDelFlag() {
        return delFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column view_project.del_flag
     *
     * @param delFlag the value for view_project.del_flag
     * @mbg.generated Fri Mar 20 15:26:48 CST 2020
     */
    public void setDelFlag(Integer delFlag) {
        this.delFlag = delFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column view_project.operator
     *
     * @return the value of view_project.operator
     * @mbg.generated Fri Mar 20 15:26:48 CST 2020
     */
    public String getOperator() {
        return operator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column view_project.operator
     *
     * @param operator the value for view_project.operator
     * @mbg.generated Fri Mar 20 15:26:48 CST 2020
     */
    public void setOperator(String operator) {
        this.operator = operator == null ? null : operator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column view_project.operator_ip
     *
     * @return the value of view_project.operator_ip
     * @mbg.generated Fri Mar 20 15:26:48 CST 2020
     */
    public String getOperatorIp() {
        return operatorIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column view_project.operator_ip
     *
     * @param operatorIp the value for view_project.operator_ip
     * @mbg.generated Fri Mar 20 15:26:48 CST 2020
     */
    public void setOperatorIp(String operatorIp) {
        this.operatorIp = operatorIp == null ? null : operatorIp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column view_project.operator_time
     *
     * @return the value of view_project.operator_time
     * @mbg.generated Fri Mar 20 15:26:48 CST 2020
     */
    public Date getOperatorTime() {
        return operatorTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column view_project.operator_time
     *
     * @param operatorTime the value for view_project.operator_time
     * @mbg.generated Fri Mar 20 15:26:48 CST 2020
     */
    public void setOperatorTime(Date operatorTime) {
        this.operatorTime = operatorTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column view_project.place
     *
     * @return the value of view_project.place
     * @mbg.generated Fri Mar 20 15:26:48 CST 2020
     */
    public Integer getPlace() {
        return place;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column view_project.place
     *
     * @param place the value for view_project.place
     * @mbg.generated Fri Mar 20 15:26:48 CST 2020
     */
    public void setPlace(Integer place) {
        this.place = place;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column view_project.work_place_name
     *
     * @return the value of view_project.work_place_name
     * @mbg.generated Fri Mar 20 15:26:48 CST 2020
     */
    public String getWorkPlaceName() {
        return workPlaceName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column view_project.work_place_name
     *
     * @param workPlaceName the value for view_project.work_place_name
     * @mbg.generated Fri Mar 20 15:26:48 CST 2020
     */
    public void setWorkPlaceName(String workPlaceName) {
        this.workPlaceName = workPlaceName == null ? null : workPlaceName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column view_project.manager_name
     *
     * @return the value of view_project.manager_name
     * @mbg.generated Fri Mar 20 15:26:48 CST 2020
     */
    public String getManagerName() {
        return managerName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column view_project.manager_name
     *
     * @param managerName the value for view_project.manager_name
     * @mbg.generated Fri Mar 20 15:26:48 CST 2020
     */
    public void setManagerName(String managerName) {
        this.managerName = managerName == null ? null : managerName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column view_project.leader_name
     *
     * @return the value of view_project.leader_name
     * @mbg.generated Fri Mar 20 15:26:48 CST 2020
     */
    public String getLeaderName() {
        return leaderName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column view_project.leader_name
     *
     * @param leaderName the value for view_project.leader_name
     * @mbg.generated Fri Mar 20 15:26:48 CST 2020
     */
    public void setLeaderName(String leaderName) {
        this.leaderName = leaderName == null ? null : leaderName.trim();
    }
}