package cn.edu.upc.manage.model;

/**
 * @author zhenwei
 * @date 2020/3/20
 */
public class ViewGroupUser {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column view_group_user.id
     *
     * @mbg.generated Fri Mar 20 23:11:58 CST 2020
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column view_group_user.project_id
     *
     * @mbg.generated Fri Mar 20 23:11:58 CST 2020
     */
    private Integer projectId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column view_group_user.group_id
     *
     * @mbg.generated Fri Mar 20 23:11:58 CST 2020
     */
    private Integer groupId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column view_group_user.group_name
     *
     * @mbg.generated Fri Mar 20 23:11:58 CST 2020
     */
    private String groupName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column view_group_user.user_id
     *
     * @mbg.generated Fri Mar 20 23:11:58 CST 2020
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column view_group_user.real_name
     *
     * @mbg.generated Fri Mar 20 23:11:58 CST 2020
     */
    private String realName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column view_group_user.user_type
     *
     * @mbg.generated Fri Mar 20 23:11:58 CST 2020
     */
    private Byte userType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column view_group_user.content
     *
     * @mbg.generated Fri Mar 20 23:11:58 CST 2020
     */
    private String content;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column view_group_user.id
     *
     * @return the value of view_group_user.id
     * @mbg.generated Fri Mar 20 23:11:58 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column view_group_user.id
     *
     * @param id the value for view_group_user.id
     * @mbg.generated Fri Mar 20 23:11:58 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column view_group_user.project_id
     *
     * @return the value of view_group_user.project_id
     * @mbg.generated Fri Mar 20 23:11:58 CST 2020
     */
    public  Integer getProjectId() {
        return projectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column view_group_user.project_id
     *
     * @param projectId the value for view_group_user.project_id
     * @mbg.generated Fri Mar 20 23:11:58 CST 2020
     */
    public void setProjectId(Integer projectId) {
        this.projectId = projectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column view_group_user.group_id
     *
     * @return the value of view_group_user.group_id
     * @mbg.generated Fri Mar 20 23:11:58 CST 2020
     */
    public Integer getGroupId() {
        return groupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column view_group_user.group_id
     *
     * @param groupId the value for view_group_user.group_id
     * @mbg.generated Fri Mar 20 23:11:58 CST 2020
     */
    public void setGroupId(Integer groupId) {
        this.groupId = groupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column view_group_user.group_name
     *
     * @return the value of view_group_user.group_name
     * @mbg.generated Fri Mar 20 23:11:58 CST 2020
     */
    public String getGroupName() {
        return groupName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column view_group_user.group_name
     *
     * @param groupName the value for view_group_user.group_name
     * @mbg.generated Fri Mar 20 23:11:58 CST 2020
     */
    public void setGroupName(String groupName) {
        this.groupName = groupName == null ? null : groupName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column view_group_user.user_id
     *
     * @return the value of view_group_user.user_id
     * @mbg.generated Fri Mar 20 23:11:58 CST 2020
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column view_group_user.user_id
     *
     * @param userId the value for view_group_user.user_id
     * @mbg.generated Fri Mar 20 23:11:58 CST 2020
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column view_group_user.real_name
     *
     * @return the value of view_group_user.real_name
     * @mbg.generated Fri Mar 20 23:11:58 CST 2020
     */
    public String getRealName() {
        return realName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column view_group_user.real_name
     *
     * @param realName the value for view_group_user.real_name
     * @mbg.generated Fri Mar 20 23:11:58 CST 2020
     */
    public void setRealName(String realName) {
        this.realName = realName == null ? null : realName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column view_group_user.user_type
     *
     * @return the value of view_group_user.user_type
     * @mbg.generated Fri Mar 20 23:11:58 CST 2020
     */
    public Byte getUserType() {
        return userType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column view_group_user.user_type
     *
     * @param userType the value for view_group_user.user_type
     * @mbg.generated Fri Mar 20 23:11:58 CST 2020
     */
    public void setUserType(Byte userType) {
        this.userType = userType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column view_group_user.content
     *
     * @return the value of view_group_user.content
     * @mbg.generated Fri Mar 20 23:11:58 CST 2020
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column view_group_user.content
     *
     * @param content the value for view_group_user.content
     * @mbg.generated Fri Mar 20 23:11:58 CST 2020
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }
}