package cn.edu.upc.manage.model;

import java.util.Date;

public class ViewUser {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column view_user.id
     *
     * @mbg.generated Sun Mar 22 17:13:45 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column view_user.user_name
     *
     * @mbg.generated Sun Mar 22 17:13:45 CST 2020
     */
    private String userName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column view_user.password
     *
     * @mbg.generated Sun Mar 22 17:13:45 CST 2020
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column view_user.real_name
     *
     * @mbg.generated Sun Mar 22 17:13:45 CST 2020
     */
    private String realName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column view_user.work_place
     *
     * @mbg.generated Sun Mar 22 17:13:45 CST 2020
     */
    private Integer workPlace;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column view_user.technology
     *
     * @mbg.generated Sun Mar 22 17:13:45 CST 2020
     */
    private Integer technology;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column view_user.email
     *
     * @mbg.generated Sun Mar 22 17:13:45 CST 2020
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column view_user.field_position
     *
     * @mbg.generated Sun Mar 22 17:13:45 CST 2020
     */
    private Integer fieldPosition;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column view_user.role
     *
     * @mbg.generated Sun Mar 22 17:13:45 CST 2020
     */
    private Integer role;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column view_user.creat_time
     *
     * @mbg.generated Sun Mar 22 17:13:45 CST 2020
     */
    private Date creatTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column view_user.del_flag
     *
     * @mbg.generated Sun Mar 22 17:13:45 CST 2020
     */
    private Integer delFlag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column view_user.operator
     *
     * @mbg.generated Sun Mar 22 17:13:45 CST 2020
     */
    private String operator;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column view_user.operator_ip
     *
     * @mbg.generated Sun Mar 22 17:13:45 CST 2020
     */
    private String operatorIp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column view_user.operator_time
     *
     * @mbg.generated Sun Mar 22 17:13:45 CST 2020
     */
    private Date operatorTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column view_user.work_place_name
     *
     * @mbg.generated Sun Mar 22 17:13:45 CST 2020
     */
    private String workPlaceName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column view_user.technology_name
     *
     * @mbg.generated Sun Mar 22 17:13:45 CST 2020
     */
    private String technologyName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column view_user.role_name
     *
     * @mbg.generated Sun Mar 22 17:13:45 CST 2020
     */
    private String roleName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column view_user.id
     *
     * @return the value of view_user.id
     *
     * @mbg.generated Sun Mar 22 17:13:45 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column view_user.id
     *
     * @param id the value for view_user.id
     *
     * @mbg.generated Sun Mar 22 17:13:45 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column view_user.user_name
     *
     * @return the value of view_user.user_name
     *
     * @mbg.generated Sun Mar 22 17:13:45 CST 2020
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column view_user.user_name
     *
     * @param userName the value for view_user.user_name
     *
     * @mbg.generated Sun Mar 22 17:13:45 CST 2020
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column view_user.password
     *
     * @return the value of view_user.password
     *
     * @mbg.generated Sun Mar 22 17:13:45 CST 2020
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column view_user.password
     *
     * @param password the value for view_user.password
     *
     * @mbg.generated Sun Mar 22 17:13:45 CST 2020
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column view_user.real_name
     *
     * @return the value of view_user.real_name
     *
     * @mbg.generated Sun Mar 22 17:13:45 CST 2020
     */
    public String getRealName() {
        return realName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column view_user.real_name
     *
     * @param realName the value for view_user.real_name
     *
     * @mbg.generated Sun Mar 22 17:13:45 CST 2020
     */
    public void setRealName(String realName) {
        this.realName = realName == null ? null : realName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column view_user.work_place
     *
     * @return the value of view_user.work_place
     *
     * @mbg.generated Sun Mar 22 17:13:45 CST 2020
     */
    public Integer getWorkPlace() {
        return workPlace;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column view_user.work_place
     *
     * @param workPlace the value for view_user.work_place
     *
     * @mbg.generated Sun Mar 22 17:13:45 CST 2020
     */
    public void setWorkPlace(Integer workPlace) {
        this.workPlace = workPlace;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column view_user.technology
     *
     * @return the value of view_user.technology
     *
     * @mbg.generated Sun Mar 22 17:13:45 CST 2020
     */
    public Integer getTechnology() {
        return technology;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column view_user.technology
     *
     * @param technology the value for view_user.technology
     *
     * @mbg.generated Sun Mar 22 17:13:45 CST 2020
     */
    public void setTechnology(Integer technology) {
        this.technology = technology;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column view_user.email
     *
     * @return the value of view_user.email
     *
     * @mbg.generated Sun Mar 22 17:13:45 CST 2020
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column view_user.email
     *
     * @param email the value for view_user.email
     *
     * @mbg.generated Sun Mar 22 17:13:45 CST 2020
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column view_user.field_position
     *
     * @return the value of view_user.field_position
     *
     * @mbg.generated Sun Mar 22 17:13:45 CST 2020
     */
    public Integer getFieldPosition() {
        return fieldPosition;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column view_user.field_position
     *
     * @param fieldPosition the value for view_user.field_position
     *
     * @mbg.generated Sun Mar 22 17:13:45 CST 2020
     */
    public void setFieldPosition(Integer fieldPosition) {
        this.fieldPosition = fieldPosition;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column view_user.role
     *
     * @return the value of view_user.role
     *
     * @mbg.generated Sun Mar 22 17:13:45 CST 2020
     */
    public Integer getRole() {
        return role;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column view_user.role
     *
     * @param role the value for view_user.role
     *
     * @mbg.generated Sun Mar 22 17:13:45 CST 2020
     */
    public void setRole(Integer role) {
        this.role = role;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column view_user.creat_time
     *
     * @return the value of view_user.creat_time
     *
     * @mbg.generated Sun Mar 22 17:13:45 CST 2020
     */
    public Date getCreatTime() {
        return creatTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column view_user.creat_time
     *
     * @param creatTime the value for view_user.creat_time
     *
     * @mbg.generated Sun Mar 22 17:13:45 CST 2020
     */
    public void setCreatTime(Date creatTime) {
        this.creatTime = creatTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column view_user.del_flag
     *
     * @return the value of view_user.del_flag
     *
     * @mbg.generated Sun Mar 22 17:13:45 CST 2020
     */
    public Integer getDelFlag() {
        return delFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column view_user.del_flag
     *
     * @param delFlag the value for view_user.del_flag
     *
     * @mbg.generated Sun Mar 22 17:13:45 CST 2020
     */
    public void setDelFlag(Integer delFlag) {
        this.delFlag = delFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column view_user.operator
     *
     * @return the value of view_user.operator
     *
     * @mbg.generated Sun Mar 22 17:13:45 CST 2020
     */
    public String getOperator() {
        return operator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column view_user.operator
     *
     * @param operator the value for view_user.operator
     *
     * @mbg.generated Sun Mar 22 17:13:45 CST 2020
     */
    public void setOperator(String operator) {
        this.operator = operator == null ? null : operator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column view_user.operator_ip
     *
     * @return the value of view_user.operator_ip
     *
     * @mbg.generated Sun Mar 22 17:13:45 CST 2020
     */
    public String getOperatorIp() {
        return operatorIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column view_user.operator_ip
     *
     * @param operatorIp the value for view_user.operator_ip
     *
     * @mbg.generated Sun Mar 22 17:13:45 CST 2020
     */
    public void setOperatorIp(String operatorIp) {
        this.operatorIp = operatorIp == null ? null : operatorIp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column view_user.operator_time
     *
     * @return the value of view_user.operator_time
     *
     * @mbg.generated Sun Mar 22 17:13:45 CST 2020
     */
    public Date getOperatorTime() {
        return operatorTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column view_user.operator_time
     *
     * @param operatorTime the value for view_user.operator_time
     *
     * @mbg.generated Sun Mar 22 17:13:45 CST 2020
     */
    public void setOperatorTime(Date operatorTime) {
        this.operatorTime = operatorTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column view_user.work_place_name
     *
     * @return the value of view_user.work_place_name
     *
     * @mbg.generated Sun Mar 22 17:13:45 CST 2020
     */
    public String getWorkPlaceName() {
        return workPlaceName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column view_user.work_place_name
     *
     * @param workPlaceName the value for view_user.work_place_name
     *
     * @mbg.generated Sun Mar 22 17:13:45 CST 2020
     */
    public void setWorkPlaceName(String workPlaceName) {
        this.workPlaceName = workPlaceName == null ? null : workPlaceName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column view_user.technology_name
     *
     * @return the value of view_user.technology_name
     *
     * @mbg.generated Sun Mar 22 17:13:45 CST 2020
     */
    public String getTechnologyName() {
        return technologyName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column view_user.technology_name
     *
     * @param technologyName the value for view_user.technology_name
     *
     * @mbg.generated Sun Mar 22 17:13:45 CST 2020
     */
    public void setTechnologyName(String technologyName) {
        this.technologyName = technologyName == null ? null : technologyName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column view_user.role_name
     *
     * @return the value of view_user.role_name
     *
     * @mbg.generated Sun Mar 22 17:13:45 CST 2020
     */
    public String getRoleName() {
        return roleName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column view_user.role_name
     *
     * @param roleName the value for view_user.role_name
     *
     * @mbg.generated Sun Mar 22 17:13:45 CST 2020
     */
    public void setRoleName(String roleName) {
        this.roleName = roleName == null ? null : roleName.trim();
    }
}