package cn.edu.upc.manage.model;

public class ViewGroupUser2 {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column view_group_user2.id
     *
     * @mbg.generated Sun Apr 05 17:16:10 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column view_group_user2.project_id
     *
     * @mbg.generated Sun Apr 05 17:16:10 CST 2020
     */
    private Integer projectId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column view_group_user2.group_name
     *
     * @mbg.generated Sun Apr 05 17:16:10 CST 2020
     */
    private String groupName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column view_group_user2.user_id
     *
     * @mbg.generated Sun Apr 05 17:16:10 CST 2020
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column view_group_user2.user_type
     *
     * @mbg.generated Sun Apr 05 17:16:10 CST 2020
     */
    private Byte userType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column view_group_user2.real_name
     *
     * @mbg.generated Sun Apr 05 17:16:10 CST 2020
     */
    private String realName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column view_group_user2.content
     *
     * @mbg.generated Sun Apr 05 17:16:10 CST 2020
     */
    private String content;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column view_group_user2.del_flag
     *
     * @mbg.generated Sun Apr 05 17:16:10 CST 2020
     */
    private Integer delFlag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column view_group_user2.group_user_id
     *
     * @mbg.generated Sun Apr 05 17:16:10 CST 2020
     */
    private Integer groupUserId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column view_group_user2.id
     *
     * @return the value of view_group_user2.id
     *
     * @mbg.generated Sun Apr 05 17:16:10 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column view_group_user2.id
     *
     * @param id the value for view_group_user2.id
     *
     * @mbg.generated Sun Apr 05 17:16:10 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column view_group_user2.project_id
     *
     * @return the value of view_group_user2.project_id
     *
     * @mbg.generated Sun Apr 05 17:16:10 CST 2020
     */
    public Integer getProjectId() {
        return projectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column view_group_user2.project_id
     *
     * @param projectId the value for view_group_user2.project_id
     *
     * @mbg.generated Sun Apr 05 17:16:10 CST 2020
     */
    public void setProjectId(Integer projectId) {
        this.projectId = projectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column view_group_user2.group_name
     *
     * @return the value of view_group_user2.group_name
     *
     * @mbg.generated Sun Apr 05 17:16:10 CST 2020
     */
    public String getGroupName() {
        return groupName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column view_group_user2.group_name
     *
     * @param groupName the value for view_group_user2.group_name
     *
     * @mbg.generated Sun Apr 05 17:16:10 CST 2020
     */
    public void setGroupName(String groupName) {
        this.groupName = groupName == null ? null : groupName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column view_group_user2.user_id
     *
     * @return the value of view_group_user2.user_id
     *
     * @mbg.generated Sun Apr 05 17:16:10 CST 2020
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column view_group_user2.user_id
     *
     * @param userId the value for view_group_user2.user_id
     *
     * @mbg.generated Sun Apr 05 17:16:10 CST 2020
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column view_group_user2.user_type
     *
     * @return the value of view_group_user2.user_type
     *
     * @mbg.generated Sun Apr 05 17:16:10 CST 2020
     */
    public Byte getUserType() {
        return userType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column view_group_user2.user_type
     *
     * @param userType the value for view_group_user2.user_type
     *
     * @mbg.generated Sun Apr 05 17:16:10 CST 2020
     */
    public void setUserType(Byte userType) {
        this.userType = userType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column view_group_user2.real_name
     *
     * @return the value of view_group_user2.real_name
     *
     * @mbg.generated Sun Apr 05 17:16:10 CST 2020
     */
    public String getRealName() {
        return realName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column view_group_user2.real_name
     *
     * @param realName the value for view_group_user2.real_name
     *
     * @mbg.generated Sun Apr 05 17:16:10 CST 2020
     */
    public void setRealName(String realName) {
        this.realName = realName == null ? null : realName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column view_group_user2.content
     *
     * @return the value of view_group_user2.content
     *
     * @mbg.generated Sun Apr 05 17:16:10 CST 2020
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column view_group_user2.content
     *
     * @param content the value for view_group_user2.content
     *
     * @mbg.generated Sun Apr 05 17:16:10 CST 2020
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column view_group_user2.del_flag
     *
     * @return the value of view_group_user2.del_flag
     *
     * @mbg.generated Sun Apr 05 17:16:10 CST 2020
     */
    public Integer getDelFlag() {
        return delFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column view_group_user2.del_flag
     *
     * @param delFlag the value for view_group_user2.del_flag
     *
     * @mbg.generated Sun Apr 05 17:16:10 CST 2020
     */
    public void setDelFlag(Integer delFlag) {
        this.delFlag = delFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column view_group_user2.group_user_id
     *
     * @return the value of view_group_user2.group_user_id
     *
     * @mbg.generated Sun Apr 05 17:16:10 CST 2020
     */
    public Integer getGroupUserId() {
        return groupUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column view_group_user2.group_user_id
     *
     * @param groupUserId the value for view_group_user2.group_user_id
     *
     * @mbg.generated Sun Apr 05 17:16:10 CST 2020
     */
    public void setGroupUserId(Integer groupUserId) {
        this.groupUserId = groupUserId;
    }
}